apiVersion: apps/v1
kind: Deployment
metadata:
  name: wadm
  namespace: system
  labels:
    control-plane: wadm
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: wadm
  template:
    metadata:
      labels:
        control-plane: wadm
    spec:
      containers:
        - name: wadm
          image: wadm
          imagePullPolicy: Always
          env:
            - name: WADM_NATS_SERVER
              value: nats-headless:4222
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
