# A sample GPU hostgroup.
apiVersion: k8s.wasmcloud.dev/v1alpha1
kind: HostGroup
metadata:
  name: gpu
spec:
  lattice: default
  nodeSelector:
    "gpu": "true"
  resources:
    limits:
      nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
